const FETCH_POST_LIST = 'FETCH_POST_LIST';
const FETCH_POST_LIST_SUCCESS = 'FETCH_POST_LIST_SUCCESS';
const FETCH_POST_LIST_ERROR = 'FETCH_POST_LIST_ERROR';

const FETCH_POST_DETAILS = 'FETCH_POST_DETAILS';
const FETCH_POST_DETAILS_SUCCESS = 'FETCH_POST_DETAILS_SUCCESS';
const FETCH_POST_DETAILS_ERROR = 'FETCH_POST_DETAILS_ERROR';

export {
    FETCH_POST_LIST, 
    FETCH_POST_LIST_SUCCESS,
    FETCH_POST_LIST_ERROR,
    FETCH_POST_DETAILS,
    FETCH_POST_DETAILS_SUCCESS,
    FETCH_POST_DETAILS_ERROR
}