// Constants
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
const FETCH_USER_DETAILS_ERROR = 'FETCH_USER_DETAILS_ERROR';


export {
    INCREMENT,
    DECREMENT,
    FETCH_USER_DETAILS,
    FETCH_USER_DETAILS_SUCCESS,
    FETCH_USER_DETAILS_ERROR
}